.TH "RESIN" "1" "January 2015" "" ""
.SH "NAME"
\fBresin\fR \- command line tool to interact with resin\.io
.SH SYNOPSIS
.P
\fBresin\fR [options] <command>
.SH DESCRIPTION
.P
\fBresin\fR is a powerful command line application to interact, develop and deploy resin\.io applications and devices\.
.SH COPYRIGHT
.P
resin is Copyright (C) 2014 Resin\.io https://resin\.io
