.\" Generated with Ronnjs 0.4.0
.\" http://github.com/kapouer/ronnjs
.
.TH "RESIN" "1" "December 2014" "" ""
.
.SH "NAME"
\fBresin\fR \-\- command line tool to interact with resin\.io
.
.SH "SYNOPSIS"
\fBresin\fR [options] <command>
.
.SH "DESCRIPTION"
\fBresin\fR is a powerful command line application to interact, develop and deploy resin\.io applications and devices\.
.
.SH "COPYRIGHT"
resin is Copyright (C) 2014 Resin\.io \fIhttps://resin\.io\fR