---
name: finalize release
# https://github.com/product-os/flowzone/tree/master/.github/actions
inputs:
  json:
    description: "JSON stringified object containing all the inputs from the calling workflow"
    required: true
  secrets:
    description: "JSON stringified object containing all the secrets from the calling workflow"
    required: true
  variables:
    description: "JSON stringified object containing all the variables from the calling workflow"
    required: true

  # --- custom environment
  NODE_VERSION:
    type: string
    default: '22.x'
  VERBOSE:
    type: string
    default: "true"

runs:
  # https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
  using: "composite"
  steps:
    # https://github.com/actions/setup-node#caching-global-packages-data
    - name: Setup Node.js
      uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
      with:
        node-version: ${{ inputs.NODE_VERSION }}
        cache: npm

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@b47578312673ae6fa5b5096b330d9fbac3d116df # v4.2.1
      with:
        aws-region: ${{ fromJSON(inputs.variables).AWS_REGION || 'us-east-1' }}
        role-session-name: github-${{ github.job }}-${{ github.run_id }}-${{ github.run_attempt }}
        # balena-io/environments-bases: aws/balena/github-openid-policy.yml
        role-to-assume: ${{ fromJSON(inputs.variables).AWS_IAM_ROLE }}

    - name: Promote to stable channel
      shell: bash
      run: |
        set -ea

        SHA="${REF_SHA:0:7}"
        VERSION=$(jq -r .version < package.json)

        npm ci
        npx oclif promote \
        --channel stable \
        --sha $SHA \
        --version $VERSION \
        --macos \
        --win \
        --ignore-missing \
        --indexes

      env:
        REF_SHA: ${{ github.event.pull_request.head.sha }}
